const dbConnection = require("../config/mongoConnection");
const data = require("../data");
const ingredients = data.ingredients;
const ingredientsList = {
  Vegetables: [
    "Beetroot",
    "Cabbage",
    "Artichoke",
    "Asparagus",
    "Avocado",
    "Beans",
    "Beetroot",
    "Bell Pepper",
    "Bitter Gourd",
    "Broccoli",
    "Brussels Sprouts",
    "Cabbage",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Corn",
    "Baby Corn",
    "Cucumber",
    "Radish",
    "Eggplant",
    "Fennel",
    "Garlic",
    "Ginger",
    "Spinach",
    "Kale",
    "Lettuce",
    "Iceberg Lettuce",
    "Romaine",
    "Mushroom",
    "Okra",
    "Olive",
    "Onion",
    "Scallions",
    "Parsley",
    "Parsnip",
    "Peas",
    "Green Chilli",
    "Potato",
    "Pumpkin",
    "Shallots",
    "Squash",
    "Sweet Potato",
    "Tomato",
    "Turnip",
    "Yam",
    "Zucchini",
  ],
  Dairy: [
    "Butter",
    "Cream",
    "Condensed Milk",
    "Curd",
    "Egg",
    "Frosting",
    "Greek Yogurt",
    "Heavy Cream",
    "Ice Cream",
    "Sour Cream",
    "Whipped Cream",
    "Yogurt",
  ],
  "Herbs & Spices": [
    "Asafoetida",
    "Basil",
    "Bay Leaf",
    "Cardamom",
    "Cayenne",
    "Celery Seeds",
    "Chilli Powder",
    "Chive",
    "Chilli Flakes",
    "Cilantro",
    "Cumin",
    "Cinnamon",
    "Clove",
    "Coriander",
    "Cumin",
    "Curry Leaves",
    "Dill",
    "Fenugreek",
    "Garlic Powder",
    "Ginger Powder",
    "Red Chilli Powder",
    "Onion Powder",
    "Oregano",
    "Paprika",
    "Parsley",
    "Rosemary",
    "Saffron",
    "Star Anise",
    "Tamarind",
    "Thyme",
    "Turmeric",
    "Pepper",
  ],
  Baking: [
    "Baking Powder",
    "Baking Soda",
    "Bread Flour",
    "Brownie Mix",
    "Cocoa Powder",
    "Cake Flour",
    "Cake Mix",
    "Chocolate Chips",
    "Corn Flour",
    "Coffe Bean",
    "Corn Starch",
    "Flour",
    "Food Coloring",
    "Gelatin",
    "Lemon Extract",
    "Muffin Mix",
    "Pancake Mix",
    "Rice Flour",
    "Yeast",
    "Sugar",
    "Maple Syrup",
    "Brown Sugar",
    "Chocolate Syrup",
    "Caramel Syrup",
    "Corn Syrup",
    "Honey",
    "Molasses",
    "Stevia",
    "Vanilla",
  ],
  "Fruits & Berries": [
    "Apple",
    "Apricot",
    "Banana",
    "Blueberry",
    "Cherry",
    "Custard Apple",
    "Fig",
    "Grape",
    "Grapefruit",
    "Guava",
    "Kiwi",
    "Lemon",
    "Lime",
    "Lychee",
    "Mandarin",
    "Mango",
    "Orange",
    "Passionfruit",
    "Papaya",
    "Peach",
    "Pear",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Raspberry",
    "Strawberry",
    "Watermelon",
  ],
};

async function main() {
  console.log("1");
  const db = await dbConnection();
  console.log("1a");
  await db.dropDatabase();
  //await db.dropCollection("ingredients");
  console.log("2");
  for (const ig in ingredientsList) {
    console.log(ig);
    ig[1].sort();
    await ingredients.create(ig[0], ig[1]);
  }
  console.log("Done seeding database");

  await db.serverConfig.close();
}

main().catch((error) => {
  console.log(error);
});
